source_list:
  - CP
#  - OL
#  - SB
#  - ADDR

OL:
  sftp_conf:
    filetype: csv
    delimiter: |
    directory: /home/ubuntu/data
    filename: receipts_delta_GBR_14_10_2017.csv

SB:
  mysql_conf:
    dbtable: testdb.TRANSACTIONSYNC
    partition_column: App_Transaction_Id
    query: "(select * from testdb.TRANSACTIONSYNC ') as t"

CP:
  s3_conf:
    s3_bucket: storage-bucket-test123
    filename: KC_Extract_1_20171009.csv

ADDR:
  mongodb_config:
    database: school
    collection: students

s3_conf:
    s3_bucket: storage-bucket-test123
    staging_dir: staging

redshift_conf:
  filetype: csv
  delimiter: |
  dbtable: PUBLIC.TXN_FCT
  dbtablewrt: PUBLIC.TXN_FCT_WRT
  query: SELECT txn_id, create_time, amount, cust_id from PUBLIC.TXN_FCT

